# Generated by Django 4.2.30 on 2026-04-18 16:27

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[
                            django.core.validators.EmailValidator(
                                message="Enter a valid email address."
                            )
                        ],
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "did",
                    models.CharField(
                        blank=True,
                        help_text="User DID (e.g., did:key:z6MkqRYqQiSgvZQdnBytw86Qbs2ZWUkGv22od...)",
                        max_length=255,
                        null=True,
                        verbose_name="Decentralized Identifier",
                    ),
                ),
                (
                    "did_document",
                    models.JSONField(
                        blank=True,
                        help_text="Full DID document as JSON",
                        null=True,
                        verbose_name="DID Document",
                    ),
                ),
                (
                    "mfa_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether TOTP-based MFA is enabled for this user",
                        verbose_name="MFA Enabled",
                    ),
                ),
                (
                    "mfa_secret",
                    models.CharField(
                        blank=True,
                        help_text="Encrypted TOTP secret (server stores hash only)",
                        max_length=64,
                        verbose_name="MFA Secret",
                    ),
                ),
                (
                    "mfa_secret_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash of TOTP secret for verification",
                        max_length=128,
                        verbose_name="MFA Secret Hash",
                    ),
                ),
                (
                    "mfa_backup_codes",
                    models.JSONField(
                        blank=True,
                        help_text="One-time backup codes for account recovery",
                        null=True,
                        verbose_name="MFA Backup Codes",
                    ),
                ),
                (
                    "mfa_last_verified",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last successful MFA verification",
                        null=True,
                        verbose_name="Last MFA Verification",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-date_joined"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="SessionAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        help_text="Django session key",
                        max_length=40,
                        verbose_name="Session Key",
                    ),
                ),
                (
                    "did",
                    models.CharField(
                        blank=True,
                        help_text="DID used for authentication",
                        max_length=255,
                        verbose_name="User DID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP Address")),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_did",
                    models.CharField(
                        blank=True,
                        help_text="DID of the user (if applicable)",
                        max_length=255,
                        verbose_name="User DID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("login_failed", "Login Failed"),
                            ("did_login", "DID Login"),
                            ("did_login_failed", "DID Login Failed"),
                            ("mfa_enabled", "MFA Enabled"),
                            ("mfa_disabled", "MFA Disabled"),
                            ("mfa_verified", "MFA Verified"),
                            ("mfa_verification_failed", "MFA Verification Failed"),
                            ("mfa_backup_used", "MFA Backup Code Used"),
                            ("register", "Registration"),
                            ("did_generated", "DID Generated"),
                            ("vc_issued", "Verifiable Credential Issued"),
                            ("vc_verified", "Verifiable Credential Verified"),
                            ("vc_verification_failed", "VC Verification Failed"),
                            ("vc_revoked", "Verifiable Credential Revoked"),
                            ("session_created", "Session Created"),
                            ("session_expired", "Session Expired"),
                            ("session_invalidated", "Session Invalidated"),
                            ("user_updated", "User Updated"),
                            ("user_deactivated", "User Deactivated"),
                            ("user_reactivated", "User Reactivated"),
                        ],
                        help_text="Type of action performed",
                        max_length=50,
                        verbose_name="Action Type",
                    ),
                ),
                (
                    "action_details",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable description of the action",
                        verbose_name="Action Details",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional action-specific data (IP, user agent, etc.)",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Client IP address",
                        null=True,
                        verbose_name="IP Address",
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="Client user agent string",
                        max_length=500,
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 checksum for integrity verification",
                        max_length=64,
                        verbose_name="Checksum",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the action occurred",
                        verbose_name="Timestamp",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User associated with this action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="accounts_au_user_id_7b1069_idx",
                    ),
                    models.Index(
                        fields=["user_did", "created_at"],
                        name="accounts_au_user_di_0d57ea_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="accounts_au_action_c683b9_idx",
                    ),
                ],
            },
        ),
    ]
