# Generated by Django 4.2.30 on 2026-04-18 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("suggestion", "UI/UX Suggestion"),
                            ("bug", "Bug Report"),
                            ("feature", "Feature Request"),
                            ("other", "Other"),
                        ],
                        default="suggestion",
                        help_text="Type of feedback",
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Brief subject of the feedback", max_length=255
                    ),
                ),
                ("message", models.TextField(help_text="Detailed feedback message")),
                (
                    "screenshot",
                    models.FileField(
                        blank=True,
                        help_text="Optional screenshot of the issue",
                        null=True,
                        upload_to="feedback/screenshots/%Y/%m/",
                    ),
                ),
                (
                    "url_context",
                    models.CharField(
                        blank=True,
                        help_text="URL where the feedback was submitted from",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("reviewed", "Reviewed"),
                            ("resolved", "Resolved"),
                            ("rejected", "Rejected"),
                        ],
                        default="new",
                        help_text="Status of the feedback",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Internal notes for admins"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who submitted the feedback",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback",
                "verbose_name_plural": "Feedbacks",
                "ordering": ["-created_at"],
            },
        ),
    ]
