# Generated by Django 4.2.30 on 2026-04-18 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestmentOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Opportunity title", max_length=255),
                ),
                ("description", models.TextField(help_text="Detailed description")),
                (
                    "min_investment",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum investment amount",
                        max_digits=12,
                    ),
                ),
                (
                    "max_investment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum investment amount",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "expected_returns_percentage",
                    models.FloatField(help_text="Expected annual returns percentage"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("funded", "Funded"),
                            ("closed", "Closed"),
                            ("expired", "Expired"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "deadline",
                    models.DateField(
                        blank=True, help_text="Application deadline", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total portfolio value",
                        max_digits=12,
                    ),
                ),
                (
                    "total_invested",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total amount invested",
                        max_digits=12,
                    ),
                ),
                (
                    "total_returns",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total returns earned",
                        max_digits=12,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio",
                "verbose_name_plural": "Portfolios",
            },
        ),
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the investment", max_length=255
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Initial investment amount",
                        max_digits=12,
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Current value of the investment",
                        max_digits=12,
                    ),
                ),
                (
                    "date_invested",
                    models.DateField(help_text="Date of initial investment"),
                ),
                (
                    "returns_percentage",
                    models.FloatField(
                        default=0.0, help_text="Percentage return on investment"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("pending", "Pending"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Document title", max_length=255)),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded file", upload_to="investor_documents/%Y/%m/"
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("tax", "Tax Document"),
                            ("statement", "Statement"),
                            ("contract", "Contract"),
                            ("report", "Report"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Document description"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, help_text="File size in bytes"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
