# Generated by Django 4.2.30 on 2026-04-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brand", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("logo", models.ImageField(blank=True, upload_to="project_logos/")),
                ("description", models.CharField(max_length=500)),
                ("link", models.URLField(blank=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ecosystem Project",
                "verbose_name_plural": "Ecosystem Projects",
                "ordering": ["order", "name"],
            },
        ),
    ]
