# Generated by Django 4.2.30 on 2026-04-28 01:58

from django.db import migrations


def populate_projects(apps, schema_editor):
    Project = apps.get_model('brand', 'Project')
    projects = [
        {
            'name': 'Byers Brands Portal',
            'description': 'The central investor portal for managing portfolios, documents, and opportunities across the Byers Brands ecosystem.',
            'link': '',
            'is_featured': True,
            'order': 1,
        },
        {
            'name': 'Polly',
            'description': 'Decentralized polling platform enabling secure, verifiable voting with DID authentication and scope-aware poll participation.',
            'link': 'https://polly.byers.brands',
            'is_featured': True,
            'order': 2,
        },
        {
            'name': 'Namechart',
            'description': 'Decentralized identity and domain management platform with DID-based authentication and credential verification.',
            'link': 'https://namechart.byers.brands',
            'is_featured': True,
            'order': 3,
        },
        {
            'name': 'Cactus',
            'description': 'Smart contract and blockchain integration platform for managing decentralized applications and token economies.',
            'link': 'https://cactus.byers.brands',
            'is_featured': False,
            'order': 4,
        },
        {
            'name': 'Sonic',
            'description': 'High-performance API gateway and microservices orchestration platform for scalable decentralized applications.',
            'link': 'https://sonic.byers.brands',
            'is_featured': False,
            'order': 5,
        },
    ]
    for proj_data in projects:
        Project.objects.get_or_create(name=proj_data['name'], defaults=proj_data)


def remove_projects(apps, schema_editor):
    Project = apps.get_model('brand', 'Project')
    Project.objects.filter(name__in=[
        'Byers Brands Portal', 'Polly', 'Namechart', 'Cactus', 'Sonic'
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("brand", "0002_project"),
    ]

    operations = [
        migrations.RunPython(populate_projects, remove_projects),
    ]
